# Generated by Django 5.1 on 2026-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadomodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
