# Generated by Django 5.1 on 2026-05-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteServicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='Clientes.clientemodel')),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='Servicios.serviciomodel')),
            ],
            options={
                'db_table': 'cliente_servicios',
                'managed': True,
                'unique_together': {('cliente', 'servicio')},
            },
        ),
    ]
