# Generated by Django 5.1 on 2026-05-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciomodel',
            options={'managed': True},
        ),
    ]
