# Generated by Django 5.1 on 2026-05-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_serviciomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteserviciomodel',
            options={'managed': True},
        ),
    ]
