# Generated by Django 5.1 on 2026-05-24 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.CASCADE, to='Eventos.eventomodel')),
            ],
            options={
                'verbose_name': 'Producto',
                'db_table': 'productos',
            },
        ),
    ]
