# Generated by Django 5.1 on 2026-05-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '__first__'),
        ('Territorio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoAventuraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoaventuras', to='Clientes.clientemodel')),
                ('territorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoaventuras', to='Territorio.territoriomodel')),
            ],
            options={
                'db_table': 'eco_aventuras',
            },
        ),
    ]
