# Generated by Django 5.1 on 2026-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAventuras', '0002_ecoaventura_nuevos_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoaventuramodel',
            name='max_actividades',
            field=models.PositiveIntegerField(default=6, help_text='Máximo de actividades permitidas'),
        ),
        migrations.AddField(
            model_name='ecoaventuramodel',
            name='min_personas',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de personas para el paquete'),
        ),
    ]
