# Generated by Django 5.1 on 2026-05-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTiposActoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente_tipos_actores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actor',
                'verbose_name_plural': 'Tipos de Actores',
                'db_table': 'tipos_actores',
            },
        ),
    ]
