# Generated by Django 5.1 on 2026-05-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actor',
                'verbose_name_plural': 'Tipos de Actores',
                'db_table': 'tipos_actores',
            },
        ),
        migrations.CreateModel(
            name='ClienteTiposActoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_actores', to='Clientes.clientemodel')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='TiposActores.tipoactormodel')),
            ],
            options={
                'db_table': 'cliente_tipos_actores',
                'managed': True,
                'unique_together': {('id_actor', 'id_tipo')},
            },
        ),
    ]
