# Generated by Django 5.1 on 2026-06-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEventoModel',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('distribucion_pago', models.TextField(blank=True, null=True)),
                ('es_local', models.BooleanField(default=True)),
                ('colaboradores', models.TextField(blank=True, null=True)),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='Eventos.eventomodel')),
            ],
            options={
                'verbose_name': 'Detalle de Evento',
                'db_table': 'detalles_eventos',
            },
        ),
    ]
