# Generated by Django 5.1 on 2026-06-25 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientemodel_id_territorio_and_more'),
        ('DetallesEventos', '0001_initial'),
        ('Estados', '0002_alter_estadomodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleeventomodel',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='detalleeventomodel',
            name='es_local',
        ),
        migrations.AddField(
            model_name='detalleeventomodel',
            name='id_colaboradores',
            field=models.ForeignKey(blank=True, db_column='id_colaboradores', limit_choices_to={'es_actor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_eventos_colaborador', to='Clientes.clientemodel'),
        ),
        migrations.AddField(
            model_name='detalleeventomodel',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estados.estadomodel'),
        ),
        migrations.AlterField(
            model_name='detalleeventomodel',
            name='distribucion_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
