# Generated by Django 5.1 on 2026-05-14 03:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'moneda',
            },
        ),
        migrations.CreateModel(
            name='Territorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_territorio', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'territorio',
            },
        ),
        migrations.CreateModel(
            name='TiposActores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Actor',
                'verbose_name_plural': 'Tipos de Actores',
                'db_table': 'tipos_actores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='', max_length=100)),
                ('servicio', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('reputacion', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5)])),
                ('es_actor', models.BooleanField(default=False)),
                ('es_lider', models.BooleanField(default=False)),
                ('es_turista', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
                ('id_tipo_moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.moneda')),
                ('id_territorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='usuarios.territorio')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_resultado', models.CharField(choices=[('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='EN_REVISION', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='usuarios.cliente')),
                ('id_lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_emitidas', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Aprobación',
                'verbose_name_plural': 'Aprobaciones',
                'db_table': 'aprobaciones',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('id_actor', 'id_lider')},
            },
        ),
        migrations.CreateModel(
            name='ClienteTiposActores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_actores', to='usuarios.cliente')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.tiposactores')),
            ],
            options={
                'db_table': 'cliente_tipos_actores',
                'unique_together': {('id_actor', 'id_tipo')},
            },
        ),
    ]
