# Generated by Django 5.1 on 2026-05-10 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('es_turista', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActorTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_formacion', models.CharField(choices=[('basica', 'Básica'), ('media', 'Media'), ('tecnica', 'Técnica'), ('universitaria', 'Universitaria'), ('posgrado', 'Posgrado')], max_length=20)),
                ('servicios', models.TextField(blank=True)),
                ('sector', models.CharField(choices=[('agro', 'Agro'), ('turismo', 'Turismo'), ('artesanias', 'Artesanías'), ('gastronomia', 'Gastronomía'), ('transporte', 'Transporte'), ('educacion', 'Educación'), ('otro', 'Otro')], max_length=20)),
                ('moneda', models.CharField(choices=[('COP', 'Peso Colombiano (COP)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)')], default='COP', max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor_territorial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actor Territorial',
                'verbose_name_plural': 'Actores Territoriales',
            },
        ),
        migrations.CreateModel(
            name='ActorRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.actorterritorial')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.role')),
            ],
            options={
                'unique_together': {('actor', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='actorterritorial',
            name='roles',
            field=models.ManyToManyField(related_name='actores', through='usuarios.ActorRol', to='usuarios.role'),
        ),
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.actorterritorial')),
            ],
            options={
                'verbose_name': 'Solicitud de Registro',
                'verbose_name_plural': 'Solicitudes de Registro',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
