# Generated by Django 5.1 on 2026-05-14 03:32

from django.contrib.auth.models import User
from django.utils import timezone
from django.db import migrations

def seed_data(apps, schema_editor):
    Moneda = apps.get_model('usuarios', 'Moneda')
    Territorio = apps.get_model('usuarios', 'Territorio')
    TiposActores = apps.get_model('usuarios', 'TiposActores')
    Cliente = apps.get_model('usuarios', 'Cliente')
    ClienteTiposActores = apps.get_model('usuarios', 'ClienteTiposActores')
    Aprobaciones = apps.get_model('usuarios', 'Aprobaciones')
    User = apps.get_model('auth', 'User')

    # Monedas
    monedas = [
        ('Peso Colombiano', 'COP'),
        ('Euro', 'EUR'),
        ('Dólar Americano', 'USD'),
    ]
    for nombre, simbolo in monedas:
        Moneda.objects.get_or_create(nombre=nombre, defaults={'simbolo': simbolo})

    # Territorios
    territorio1, _ = Territorio.objects.get_or_create(
        nombre_territorio='Valle del Cauca',
        defaults={'region': 'Cauca'}
    )
    territorio2, _ = Territorio.objects.get_or_create(
        nombre_territorio='Eje Cafetero',
        defaults={'region': 'Antioquia'}
    )

    # Tipos de actores
    tipos_nombres = ['productor', 'caminante', 'custodio', 'facilitador', 'anfitrion']
    for nombre in tipos_nombres:
        TiposActores.objects.get_or_create(nombre_tipo=nombre)

    # Líder 1
    if not User.objects.filter(email='lider1@raizviva.com').exists():
        user1 = User.objects.create_user(
            username='lider1',
            email='lider1@raizviva.com',
            password='Lider1234',
            first_name='María',
            last_name='García'
        )
        Cliente.objects.create(
            id_usuario=user1,
            nombre_completo='María García',
            id_territorio=territorio1,
            es_lider=True,
            telefono='3001234567'
        )

    # Líder 2
    if not User.objects.filter(email='lider2@raizviva.com').exists():
        user2 = User.objects.create_user(
            username='lider2',
            email='lider2@raizviva.com',
            password='Lider1234',
            first_name='Carlos',
            last_name='Martínez'
        )
        Cliente.objects.create(
            id_usuario=user2,
            nombre_completo='Carlos Martínez',
            id_territorio=territorio2,
            es_lider=True,
            telefono='3109876543'
        )

    lider1 = Cliente.objects.get(id_territorio=territorio1, es_lider=True)
    lider2 = Cliente.objects.get(id_territorio=territorio2, es_lider=True)

    # Actores en revisión
    actores_revision = [
        {'email': 'actor1@raizviva.com', 'nombre': 'Juan Pérez', 'servicio': 'Venta de cafés orgánicos', 'tipo': 'productor'},
        {'email': 'actor2@raizviva.com', 'nombre': 'Ana López', 'servicio': 'Guía de rutas ecoturísticas', 'tipo': 'caminante'},
        {'email': 'actor3@raizviva.com', 'nombre': 'Roberto Díaz', 'servicio': 'Hospedaje rural', 'tipo': 'anfitrion'},
        {'email': 'actor4@raizviva.com', 'nombre': 'Laura Castro', 'servicio': 'Talleres de cerámica', 'tipo': 'facilitador'},
        {'email': 'actor5@raizviva.com', 'nombre': 'Pedro Sánchez', 'servicio': 'Recorridos por reserva natural', 'tipo': 'custodio'},
    ]
    territorios_actors = [territorio1, territorio1, territorio1, territorio2, territorio2]
    lideres_rev = [lider1, lider1, lider1, lider2, lider2]

    for i, data in enumerate(actores_revision):
        if not User.objects.filter(email=data['email']).exists():
            user = User.objects.create_user(
                username=data['email'].split('@')[0],
                email=data['email'],
                password='Actor1234',
                first_name=data['nombre'].split()[0],
                last_name=' '.join(data['nombre'].split()[1:])
            )
            cliente = Cliente.objects.create(
                id_usuario=user,
                nombre_completo=data['nombre'],
                id_territorio=territorios_actors[i],
                servicio=data['servicio'],
                telefono='3150000000',
                es_actor=False,
                es_lider=False,
                es_turista=False
            )
            tipo = TiposActores.objects.get(nombre_tipo=data['tipo'])
            ClienteTiposActores.objects.create(id_actor=cliente, id_tipo=tipo)
            Aprobaciones.objects.create(
                id_actor=cliente,
                id_lider=lideres_rev[i],
                estado_resultado='EN_REVISION'
            )

    # Actores aprobados
    actores_aprobados = [
        {'email': 'aprobado1@raizviva.com', 'nombre': 'Sofia Torres', 'servicio': 'Comidas típicas del Valle', 'tipo': 'anfitrion'},
        {'email': 'aprobado2@raizviva.com', 'nombre': 'Miguel Rojas', 'servicio': 'Mermeladas y dulces tradicionales', 'tipo': 'productor'},
    ]
    for i, data in enumerate(actores_aprobados):
        if not User.objects.filter(email=data['email']).exists():
            user = User.objects.create_user(
                username=data['email'].split('@')[0],
                email=data['email'],
                password='Actor1234',
                first_name=data['nombre'].split()[0],
                last_name=' '.join(data['nombre'].split()[1:])
            )
            cliente = Cliente.objects.create(
                id_usuario=user,
                nombre_completo=data['nombre'],
                id_territorio=territorios_actors[i],
                servicio=data['servicio'],
                telefono='3160000000',
                es_actor=True,
                es_lider=False,
                es_turista=False
            )
            tipo = TiposActores.objects.get(nombre_tipo=data['tipo'])
            ClienteTiposActores.objects.create(id_actor=cliente, id_tipo=tipo)
            Aprobaciones.objects.create(
                id_actor=cliente,
                id_lider=lideres_rev[i],
                estado_resultado='APROBADO',
                observaciones='Solicitud aprobada. Bienvenido al ecosistema Raíz Viva.',
                fecha_respuesta=timezone.now()
            )

    # Actor rechazado
    if not User.objects.filter(email='rechazado1@raizviva.com').exists():
        user = User.objects.create_user(
            username='rechazado1',
            email='rechazado1@raizviva.com',
            password='Actor1234',
            first_name='Carlos',
            last_name='Bermúdez'
        )
        cliente = Cliente.objects.create(
            id_usuario=user,
            nombre_completo='Carlos Bermúdez',
            id_territorio=territorio1,
            servicio='Venta de artesanías y souvenir',
            telefono='3170000000',
            es_actor=False,
            es_lider=False,
            es_turista=False
        )
        tipo = TiposActores.objects.get(nombre_tipo='productor')
        ClienteTiposActores.objects.create(id_actor=cliente, id_tipo=tipo)
        Aprobaciones.objects.create(
            id_actor=cliente,
            id_lider=lider1,
            estado_resultado='RECHAZADO',
            observaciones='La información del servicio no es suficiente.',
            fecha_respuesta=timezone.now()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]