# Generated by Django 5.1 on 2026-05-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorterritorial',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='actorterritorial',
            name='nivel_formacion',
        ),
        migrations.AlterField(
            model_name='actorterritorial',
            name='sector',
            field=models.CharField(choices=[('ejemplo', 'Ejemplo')], default='ejemplo', max_length=20),
        ),
    ]
