# Generated by Django 5.1 on 2026-05-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_migrate_pendiente_to_en_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobaciones',
            name='estado_resultado',
            field=models.CharField(choices=[('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='EN_REVISION', max_length=20),
        ),
    ]
