# Generated by Django 5.1 on 2026-05-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorioModel',
            fields=[
                ('id_territorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_territorio', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'territorios',
                'managed': False,
            },
        ),
    ]
