# Generated by Django 5.1 on 2026-05-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorioModel',
            fields=[
                ('id_territorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_territorio', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='territorios_administrados', to='Clientes.clientemodel')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='Estados.estadomodel')),
            ],
            options={
                'db_table': 'territorios',
                'managed': True,
            },
        ),
    ]
