# Generated by Django 5.1 on 2026-05-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('reputacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('es_actor', models.BooleanField(default=False)),
                ('es_lider', models.BooleanField(default=False)),
                ('es_turista', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
