# Generated by Django 5.1 on 2026-05-20 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estados', '0001_initial'),
        ('Monedas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('reputacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('es_actor', models.BooleanField(default=False)),
                ('es_lider', models.BooleanField(default=False)),
                ('es_turista', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estados.estadomodel')),
                ('tipo_moneda', models.ForeignKey(blank=True, db_column='id_tipo_moneda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Monedas.monedamodel')),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
    ]
