# Generated by Django 5.1 on 2026-06-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientemodel_descripcion_clientemodel_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='id_territorio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='nombre_mostrar',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='servicio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
