# Generated by Django 5.1 on 2026-05-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientemodel_activo_clientemodel_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
