# Generated by Django 5.1 on 2026-05-28 16:21

from django.db import migrations


def migrar_activo_a_estado(apps, schema_editor):
    ClienteModel = apps.get_model('Clientes', 'ClienteModel')
    EstadoModel = apps.get_model('Estados', 'EstadoModel')

    activo_est, _ = EstadoModel.objects.get_or_create(nombre_estado='activo')
    inactivo_est, _ = EstadoModel.objects.get_or_create(nombre_estado='inactivo')

    for cliente in ClienteModel.objects.all():
        if cliente.activo:
            cliente.estado = activo_est
        else:
            cliente.estado = inactivo_est
        cliente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientemodel_es_admin'),
    ]

    operations = [
        migrations.RunPython(migrar_activo_a_estado),
    ]
