# Generated by Django 5.1 on 2026-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientemodel_es_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientemodel',
            name='activo',
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
