# Generated by Django 5.1 on 2026-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientemodel_es_admin'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE clientes DROP COLUMN activo;",
            reverse_sql="SELECT 1;",
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='direccion',
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
            ),
        ),
    ]