# Generated by Django 5.1 on 2026-06-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_remove_clientemodel_activo_clientemodel_direccion'),
    ]

    operations = [
        # This migration is now handled by 0004 with IF EXISTS clause, so it's a no-op.
        # Keeping this for migration chain integrity.
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op
            reverse_sql="SELECT 1;",
        ),
    ]
