# Generated by Django 5.1 on 2026-06-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_remove_clientemodel_activo'),
    ]

    operations = [
        # Final cleanup: safely handle if column still exists from edge cases.
        # In normal flow, this is already handled by 0004 with IF EXISTS.
        migrations.RunSQL(
            sql="ALTER TABLE clientes DROP COLUMN IF EXISTS activo;",
            reverse_sql="SELECT 1;",
        ),
    ]
