# Generated by Django 5.1 on 2026-06-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_clientemodel_direccion'),
        ('Clientes', '0005_remove_clientemodel_activo'),
    ]

    operations = [
    ]
