# Generated by Django 5.1 on 2026-06-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_merge_20260603_1935'),
        ('Clientes', '0006_merge_20260603_1946'),
    ]

    operations = [
    ]
