# Generated by Django 5.1 on 2026-06-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_remove_clientemodel_activo'),
    ]

    operations = [
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql="SELECT 1;",
        ),
    ]
