# Generated by Django 5.1 on 2026-05-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariomodel',
            name='categoria',
            field=models.CharField(default='sugerencia', max_length=100),
        ),
        migrations.AddField(
            model_name='comentariomodel',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100),
        ),
        migrations.AddField(
            model_name='comentariomodel',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comentariomodel',
            name='visible_para',
            field=models.CharField(default='admin_growth', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentariomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
