# Generated by Django 5.1 on 2026-05-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0002_comentariomodel_categoria_comentariomodel_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariomodel',
            name='categoria',
            field=models.CharField(choices=[('sugerencia', 'Sugerencia'), ('bug', 'Bug'), ('mejora', 'Mejora'), ('otro', 'Otro')], default='sugerencia', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentariomodel',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'Revision'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=100),
        ),
    ]
