# Generated by Django 5.1 on 2026-05-28 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0003_alter_comentariomodel_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariomodel',
            name='prioridad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
