# Generated by Django 5.1 on 2026-05-28 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0004_alter_comentariomodel_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentariomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
