# Generated by Django 5.1 on 2026-05-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionModel',
            fields=[
                ('id_aprobacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado_resultado', models.CharField(choices=[('EN_REVISION', 'En Revision'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='EN_REVISION', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('id_actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='Clientes.clientemodel')),
                ('id_lider', models.ForeignKey(db_column='id_lider', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_emitidas', to='Clientes.clientemodel')),
            ],
            options={
                'verbose_name': 'Aprobacion',
                'verbose_name_plural': 'Aprobaciones',
                'db_table': 'aprobaciones',
                'ordering': ['-fecha_solicitud'],
                'managed': True,
            },
        ),
    ]
