# Generated by Django 5.1 on 2026-05-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuponModel',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('usos', models.IntegerField(default=1)),
                ('veces_usado', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cupon',
                'verbose_name_plural': 'Cupones',
                'db_table': 'cupones',
            },
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'DECLINED'), (4, 'EXPIRED')], default=1)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='PagoLogModel',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('REQUEST', 'Request'), ('RESPONSE', 'Response'), ('ERROR', 'Error'), ('WEBHOOK', 'Webhook')], max_length=20)),
                ('payload', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_pago', models.ForeignKey(blank=True, db_column='id_pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='Pagos.pagomodel')),
            ],
            options={
                'verbose_name': 'Pago Log',
                'verbose_name_plural': 'Pago Logs',
                'db_table': 'pago_logs',
            },
        ),
        migrations.CreateModel(
            name='TransaccionMPModel',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('mp_payment_id', models.CharField(max_length=100, unique=True)),
                ('mp_status', models.CharField(max_length=50)),
                ('mp_payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField()),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.PROTECT, to='Pagos.pagomodel')),
            ],
            options={
                'verbose_name': 'Transaccion MercadoPago',
                'verbose_name_plural': 'Transacciones MercadoPago',
                'db_table': 'transacciones_mp',
            },
        ),
    ]
