# Generated by Django 5.1 on 2026-06-10 20:28

import Eventos.EventoModel
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategoriasEventos', '0001_initial'),
        ('Estados', '0002_alter_estadomodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoModel',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('id_actor_principal', models.IntegerField(blank=True, null=True)),
                ('id_territorio', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('costo_evento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacidad', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('es_gratuito', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=Eventos.EventoModel.ruta_imagen_evento)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CategoriasEventos.categoriaeventomodel')),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estados.estadomodel')),
            ],
            options={
                'verbose_name': 'Evento',
                'db_table': 'eventos',
            },
        ),
    ]
