# Generated by Django 5.1 on 2026-05-14 01:24

import Eventos.EventoModel
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estados', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoModel',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('id_actor_principal', models.IntegerField(blank=True, null=True)),
                ('id_territorio', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('costo_evento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacidad', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('es_gratuito', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=Eventos.EventoModel.ruta_imagen_evento)),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estados.estadomodel')),
            ],
            options={
                'verbose_name': 'Evento',
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='DetalleEventoModel',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('distribucion_pago', models.TextField(blank=True, null=True)),
                ('es_local', models.BooleanField(default=True)),
                ('colaboradores', models.TextField(blank=True, null=True)),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='Eventos.eventomodel')),
            ],
            options={
                'verbose_name': 'Detalle de Evento',
                'db_table': 'detalles_eventos',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.CASCADE, to='Eventos.eventomodel')),
            ],
            options={
                'verbose_name': 'Producto',
                'db_table': 'productos',
            },
        ),
    ]
