# Generated by Django 5.1 on 2026-06-04 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EcoAventuras', '0002_ecoaventura_nuevos_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paquete',
            },
        ),
        migrations.CreateModel(
            name='PaqueteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_reserva', models.DateField(blank=True, null=True)),
                ('num_personas', models.PositiveIntegerField(default=1)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('ecoaventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoAventuras.ecoaventuramodel')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Paquete.paquete')),
            ],
            options={
                'db_table': 'paquete_item',
                'unique_together': {('paquete', 'ecoaventura', 'fecha_reserva', 'num_personas')},
            },
        ),
    ]
