# Generated by Django 5.1 on 2026-06-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAventuras', '0002_ecoaventura_nuevos_campos'),
        ('Paquete', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paqueteitem',
            unique_together={('paquete', 'ecoaventura', 'fecha_reserva')},
        ),
    ]
