# Generated by Django 5.1 on 2026-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paquete', '0002_alter_paqueteitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_personas', models.PositiveIntegerField(default=1)),
                ('max_personas', models.PositiveIntegerField(default=20)),
                ('max_actividades', models.PositiveIntegerField(default=6)),
                ('fechas_bloqueadas', models.JSONField(blank=True, default=list)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reglas_config',
            },
        ),
    ]
